Algoritmo "alvaroqfez"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/08/2023
Var
// Seção de Declarações das variáveis 
    nome: caractere
    repet, i: inteiro
    n1: vetor[0..4] de caractere
       

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
escreval("Digite um nome: ")
leia(n1[i])
i <- i+1
repet <- repet +1
ate (repet=5)

Fimalgoritmo