Algoritmo "albaro"
// Professor   : ALVARO O CARA
// Data atual  : 02/08/2023
Var
// Seção de Declarações das variáveis 
nome:caractere
idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("qual seu nome?")
leia(nome)
escreval("Quantos anos vc tem?")
leia(idade)

escolha (idade)
caso 0 ate 2
escreval("Vá para sala 2")
caso 3 ate 5
escreval("Vá para sala 10")
caso 6 ate 8
escreval("Vá para sala 15")
caso 9 ate 10
escreval("Vá para sala 20")
   fimescolha


Fimalgoritmo