Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/08/2023
Var
// Seção de Declarações das variáveis 
n1, i: inteiro
nmr: vetor[0..4] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto (n1<5)faca
n1<-n1+1
escreval("digite 5 quaisquer")
leia(nmr[i])
escreval("você digitou: ", nmr[i])
i<-i+1
fimenquanto


Fimalgoritmo