Algoritmo "alvaroqfez"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/08/2023
Var
// Seção de Declarações das variáveis 
par: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para par de 100 ate 50 passo -2 faça
escreval(par, " ")
fimpara

Fimalgoritmo